/* XulqskorAI landing page — RU / UZ translations.
   Keys are the exact English strings rendered on the page (static HTML and
   strings generated by the landing script). English is the source; anything
   without an entry stays in English (brand names, codes, citations). */
window.XS_TR = {
ru: {
  "Film": "Видео", "Engine": "Движок", "Dimensions": "Измерения", "Integration": "Интеграция",
  "Pricing": "Цены", "Roadmap": "Дорожная карта", "FAQ": "Вопросы", "Team": "Команда",
  "MENU": "МЕНЮ", "Menu": "Меню", "Switch theme": "Сменить тему", "Sign in": "Войти",
  "Request a pilot": "Запросить пилот", "Request a pilot →": "Запросить пилот →",
  "See the engine": "Как это работает", "Replay animation": "Повторить анимацию",

  "PILOT PROGRAMME OPEN · TASHKENT": "ПИЛОТНАЯ ПРОГРАММА ОТКРЫТА · ТАШКЕНТ",
  "A 10–15 minute adaptive behavioural assessment returns a six-dimension risk profile for applicants with no credit file — a decision signal where the bureau returns nothing.": "Адаптивная поведенческая оценка за 10–15 минут даёт профиль риска по шести измерениям для заявителей без кредитной истории — сигнал для решения там, где бюро не возвращает ничего.",
  "item bank": "вопросов в банке", "dimensions": "измерений", "minutes": "минут", "languages": "языка",
  "APPLICANT · UZ-4471": "ЗАЯВИТЕЛЬ · UZ-4471", "APPLICANT UZ-4471": "ЗАЯВИТЕЛЬ UZ-4471",
  "LIVE": "ОНЛАЙН", "SCORE": "БАЛЛ", "Band B · Moderate": "Категория B · Умеренный риск",
  "No bureau file. Strong self-control and planning; conscientiousness below cohort median.": "Нет данных в бюро. Сильные самоконтроль и планирование; добросовестность ниже медианы группы.",
  "VALIDITY · PASSED": "ДОСТОВЕРНОСТЬ · ПРОЙДЕНА", "11m 42s · 38 items": "11 мин 42 с · 38 вопросов",

  "No credit file required": "Кредитная история не нужна", "NO CREDIT FILE REQUIRED": "КРЕДИТНАЯ ИСТОРИЯ НЕ НУЖНА",
  "Adaptive item selection": "Адаптивный подбор вопросов", "ADAPTIVE ITEM SELECTION": "АДАПТИВНЫЙ ПОДБОР ВОПРОСОВ",
  "Anti-cheat validity layer": "Защита от недобросовестных ответов", "ANTI-CHEAT VALIDITY LAYER": "ЗАЩИТА ОТ НЕДОБРОСОВЕСТНЫХ ОТВЕТОВ",
  "REST API + webhooks": "REST API + вебхуки", "REST API + WEBHOOKS": "REST API + ВЕБХУКИ",
  "Six behavioural dimensions": "Шесть поведенческих измерений", "SIX BEHAVIOURAL DIMENSIONS": "ШЕСТЬ ПОВЕДЕНЧЕСКИХ ИЗМЕРЕНИЙ",
  "Result in 10–15 minutes": "Результат за 10–15 минут", "RESULT IN 10–15 MINUTES": "РЕЗУЛЬТАТ ЗА 10–15 МИНУТ",
  "Bank-side admin console": "Консоль для банка", "BANK-SIDE ADMIN CONSOLE": "КОНСОЛЬ ДЛЯ БАНКА",

  "FILM — 2 MIN": "ВИДЕО — 2 МИН", "Watch the whole idea in two minutes.": "Вся идея за две минуты.",
  "What the assessment looks like from the applicant's side, and what lands on the underwriter's desk.": "Как оценка выглядит для заявителя и что получает кредитный аналитик.",
  "XulqskorAI — how behavioural scoring works": "XulqskorAI — как работает поведенческий скоринг",
  "UZ · SUBTITLES RU / EN": "UZ · СУБТИТРЫ RU / EN", "XulqskorAI film": "Видео XulqskorAI",

  "FOR APPLICANTS": "ДЛЯ ЗАЯВИТЕЛЕЙ",
  "Have no credit history? Build a profile that speaks for you.": "Нет кредитной истории? Создайте профиль, который говорит за вас.",
  "Register as an individual or a business, take the assessment once, and carry the result to any partner institution. You decide who sees it — sharing needs a consent code you generate.": "Зарегистрируйтесь как физическое или юридическое лицо, пройдите оценку один раз и используйте результат в любой партнёрской организации. Вы решаете, кто его увидит: для доступа нужен код согласия, который создаёте вы.",
  "Create an account": "Создать аккаунт", "Try the assessment": "Пройти оценку",
  "Free for applicants": "Бесплатно для заявителей", "One attempt every 90 days": "Одна попытка раз в 90 дней",
  "Shared only with your consent": "Передаётся только с вашего согласия",
  "A market trader taking the assessment on her phone": "Предпринимательница с рынка проходит оценку на телефоне",
  "Ten years trading. No credit file.": "Десять лет в торговле. Нет кредитной истории.", "ITEM 12 / 38": "ВОПРОС 12 / 38",
  "Register": "Регистрация", "Phone or email, as an individual or a legal entity. Two minutes.": "Телефон или e-mail, как физическое или юридическое лицо. Две минуты.",
  "Answer the questions": "Ответьте на вопросы", "30–45 adaptive items, 10–15 minutes, in your language. No documents.": "30–45 адаптивных вопросов, 10–15 минут, на вашем языке. Без документов.",
  "Keep your profile": "Сохраните профиль", "Score, six dimensions, personal recommendations, and a shareable consent code.": "Балл, шесть измерений, личные рекомендации и код согласия для передачи.",

  "01 — THE GAP": "01 — ПРОБЕЛ", "The file is empty. The person is not.": "Досье пустое. Человек — нет.",
  "When an applicant has never held a loan, a card, or a registered income stream, the bureau returns a blank. The underwriter is left with a choice between two bad options: decline a creditworthy person, or approve on intuition.": "Если у заявителя никогда не было кредита, карты или официального дохода, бюро возвращает пустой ответ. У кредитного аналитика остаются два плохих варианта: отказать платёжеспособному человеку или одобрить на интуиции.",
  "XulqskorAI produces a structured, comparable signal where none existed — not a replacement for your scorecard, an additional input to it.": "XulqskorAI даёт структурированный, сопоставимый сигнал там, где его не было. Это не замена вашей скоринговой модели, а дополнительный вход для неё.",
  "A credit officer reviewing an application": "Кредитный специалист рассматривает заявку",
  "BUREAU RESPONSE": "ОТВЕТ БЮРО", "NO RECORDS FOUND": "ЗАПИСЕЙ НЕ НАЙДЕНО",
  "structured risk profile returned to your underwriting queue via API": "структурированный профиль риска поступает в вашу очередь рассмотрения через API",

  "02 — THE FLOW": "02 — ПРОЦЕСС", "From application link to underwriting signal.": "От ссылки на заявку до сигнала для решения.",
  "Four stages. No integration required to start — a link works.": "Четыре этапа. Для старта интеграция не нужна — достаточно ссылки.",
  "Applicant receives a link": "Заявитель получает ссылку",
  "Sent by your officer, embedded in your form, or opened in branch on a tablet. No app, no bureau lookup, no document upload.": "Её отправляет ваш сотрудник, она встроена в вашу форму или открывается на планшете в отделении. Без приложения, запроса в бюро и загрузки документов.",
  "Adaptive assessment runs": "Проходит адаптивная оценка",
  "Each answer narrows the next item. A 500-item bank means no two sessions follow the same path, which makes answers much harder to memorise or coach.": "Каждый ответ определяет следующий вопрос. Банк из 500 вопросов означает, что сессии не повторяются, поэтому ответы гораздо сложнее заучить или подсказать.",
  "Validity layer screens the session": "Слой достоверности проверяет сессию",
  "Response latency, answer streaks, internal contradictions and window-switching are scored. Suspect sessions are flagged for review, not silently scored.": "Оцениваются время ответа, серии одинаковых ответов, внутренние противоречия и переключение окон. Подозрительные сессии отправляются на проверку, а не оцениваются молча.",
  "Profile lands in your queue": "Профиль попадает в вашу очередь",
  "Overall score, band, six dimension scores, validity verdict and reasoning — in the console or pushed to your systems over the API.": "Общий балл, категория, баллы по шести измерениям, вердикт достоверности и обоснование — в консоли или в ваших системах через API.",
  "ITEM SELECTION · POSTERIOR UPDATE": "ПОДБОР ВОПРОСОВ · ОБНОВЛЕНИЕ ОЦЕНКИ",
  "Response latency": "Время ответа", "Answer streaks": "Серии ответов", "Internal consistency": "Внутренняя согласованность",
  "Window focus": "Фокус окна", "PASS": "ОК", "REVIEW": "ПРОВЕРКА",
  "STAGE 00": "ЭТАП 00", "STAGE 01": "ЭТАП 01", "STAGE 02": "ЭТАП 02", "STAGE 03": "ЭТАП 03", "STAGE 04": "ЭТАП 04", "STAGE 05": "ЭТАП 05",

  "03 — THE ENGINE": "03 — ДВИЖОК", "Signals in. Behavioural profile out. Matched to your product.": "На входе — сигналы. На выходе — поведенческий профиль, подобранный под ваш продукт.",
  "Every answer is distributed across six dimensions, checked by the validity layer, then fitted against the risk appetite of the product being applied for.": "Каждый ответ распределяется по шести измерениям, проверяется слоем достоверности и сопоставляется с риск-аппетитом запрашиваемого продукта.",
  "Answers": "Ответы", "500-item adaptive bank": "адаптивный банк из 500 вопросов",
  "Response dynamics": "Динамика ответов", "latency, hesitation, consistency": "скорость, колебания, согласованность",
  "Validity checks": "Проверки достоверности", "contradiction pairs, window focus": "пары-противоречия, фокус окна",
  "BEHAVIOURAL": "ПОВЕДЕНЧЕСКИЙ", "PRODUCT FIT": "СООТВЕТСТВИЕ ПРОДУКТУ",
  "Microfinance": "Микрофинансы", "Bank loan": "Банковский кредит", "BNPL / insurance": "BNPL / страхование",
  "1 · Signal": "1 · Сигнал", "2 · Profile": "2 · Профиль", "3 · Score": "3 · Балл", "4 · Fit": "4 · Соответствие",
  "1 · SIGNAL": "1 · СИГНАЛ", "2 · PROFILE": "2 · ПРОФИЛЬ", "3 · SCORE": "3 · БАЛЛ", "4 · FIT": "4 · СООТВЕТСТВИЕ",

  "04 — WHAT IS MEASURED": "04 — ЧТО ИЗМЕРЯЕТСЯ", "Six dimensions, scored independently.": "Шесть измерений, каждое оценивается отдельно.",
  "Each dimension is derived from psychometric constructs in the published behavioural-credit literature and mapped to items in the bank. Hover a dimension to isolate it.": "Каждое измерение основано на психометрических конструктах из опубликованных исследований поведенческого кредитования и связано с вопросами банка. Наведите на измерение, чтобы выделить его.",
  "Responsibility": "Ответственность", "Integrity": "Честность", "Self-control": "Самоконтроль",
  "Risk control": "Контроль риска", "Money habits": "Финансовые привычки", "Planning": "Планирование",
  "Follow-through on commitments — does the applicant finish what they start, and honour arrangements without external pressure?": "Выполнение обязательств: доводит ли заявитель начатое до конца и соблюдает ли договорённости без внешнего давления?",
  "Consistency between stated intent and reported behaviour, cross-checked by contradictory item pairs across the session.": "Согласованность заявленных намерений и описанного поведения, перепроверяемая парами противоречащих вопросов в течение сессии.",
  "Impulse regulation under pressure: delayed gratification, reaction to windfalls, and spending under emotional load.": "Контроль импульсов под давлением: отложенное вознаграждение, реакция на неожиданный доход и траты в эмоциональном состоянии.",
  "Attitude to downside exposure — how the applicant sizes a bet, and whether they hold a buffer against shocks.": "Отношение к риску потерь: какой размер ставки выбирает заявитель и держит ли он запас на случай потрясений.",
  "Everyday money mechanics: tracking, prioritising obligations, and behaviour in a cash shortfall.": "Повседневное обращение с деньгами: учёт, приоритет обязательств и поведение при нехватке средств.",
  "Horizon length and structure — whether decisions are made against a plan or reactively, month to month.": "Горизонт и структура: принимаются ли решения по плану или реактивно, от месяца к месяцу.",

  "05 — TRY IT": "05 — ПОПРОБУЙТЕ", "Three items. Watch the profile move.": "Три вопроса. Смотрите, как меняется профиль.",
  "A miniature of the real assessment — the live version runs 30–45 adaptive items across the full bank.": "Миниатюра настоящей оценки: полная версия задаёт 30–45 адаптивных вопросов из всего банка.",
  "ITEM": "ВОПРОС", "LIVE PROFILE": "ПРОФИЛЬ ОНЛАЙН", "AWAITING INPUT": "ОЖИДАНИЕ ОТВЕТА", "Reset": "Сбросить",
  "A supplier offers a 20% discount if you pay for six months up front. It would take most of your cash buffer.": "Поставщик предлагает скидку 20% при оплате за шесть месяцев вперёд. Это заберёт большую часть вашего денежного запаса.",
  "Take it — the discount is guaranteed money": "Соглашусь — скидка это гарантированная выгода",
  "Negotiate a smaller prepayment for a partial discount": "Договорюсь о меньшей предоплате за частичную скидку",
  "Decline — the buffer is not for this": "Откажусь — запас не для этого",
  "A repayment is due on the 10th. On the 8th an urgent family expense comes up that would use the same money.": "Платёж по кредиту — 10-го числа. 8-го возникают срочные семейные расходы на ту же сумму.",
  "Call the lender on the 8th and agree a new date": "Позвоню кредитору 8-го и договорюсь о новой дате",
  "Pay the family expense, tell the lender afterwards": "Оплачу семейные расходы, кредитору сообщу потом",
  "Borrow short-term elsewhere to cover both": "Займу на короткий срок в другом месте, чтобы покрыть оба",
  "Your income this month is 40% above normal.": "В этом месяце ваш доход на 40% выше обычного.",
  "Buy something that has been waiting a long time": "Куплю то, что давно откладывал(а)",
  "Pay ahead on existing obligations": "Досрочно погашу текущие обязательства",
  "Hold it as buffer and decide next month": "Отложу в запас и решу в следующем месяце",
  "Profile drafted": "Профиль составлен",
  "Three items moved six dimensions. The production assessment runs 30–45 items and adds a validity layer on top.": "Три вопроса изменили шесть измерений. Полная оценка задаёт 30–45 вопросов и добавляет слой проверки достоверности.",
  "Illustrative only. Scores shown here are produced by a simplified demo function, not the production model.": "Только для иллюстрации. Баллы здесь рассчитывает упрощённая демо-функция, а не рабочая модель.",

  "06 — INTEGRATION": "06 — ИНТЕГРАЦИЯ", "Start with a link. Integrate when you're ready.": "Начните со ссылки. Интегрируйте, когда будете готовы.",
  "A pilot needs no engineering time on your side: send applicants a link, read results in the console. When the signal proves itself, move it into your origination flow over the API.": "Пилот не требует работы ваших разработчиков: отправьте заявителям ссылку и смотрите результаты в консоли. Когда сигнал подтвердит свою ценность, встройте его в процесс выдачи через API.",
  "Hosted link": "Ссылка на нашей платформе", "Per-applicant URL, expires after completion. Zero integration.": "Отдельная ссылка для каждого заявителя, истекает после прохождения. Без интеграции.",
  "REST API": "REST API", "Create a session, poll or receive a webhook, pull the full profile.": "Создайте сессию, получите вебхук или опросите статус и загрузите полный профиль.",
  "Embedded / white-label": "Встраивание / white-label", "Your brand, your domain, inside your existing application journey.": "Ваш бренд и ваш домен внутри вашего текущего процесса подачи заявки.",
  "WHAT YOUR SYSTEM RECEIVES": "ЧТО ПОЛУЧАЕТ ВАША СИСТЕМА", "PER APPLICANT": "ПО КАЖДОМУ ЗАЯВИТЕЛЮ",
  "Applicant reference": "Идентификатор заявителя", "Your own ID for the person — we never need their name to score them.": "Ваш собственный ID — для оценки нам не нужно имя человека.",
  "Overall score": "Общий балл", "0 – 100, comparable across applicants and over time.": "0 – 100, сопоставим между заявителями и во времени.",
  "Band": "Категория", "A to D, so an officer can act without reading the detail.": "От A до D, чтобы специалист мог действовать, не читая подробностей.",
  "Six dimension scores": "Баллы по шести измерениям", "Responsibility, integrity, self-control, risk control, money habits, planning.": "Ответственность, честность, самоконтроль, контроль риска, финансовые привычки, планирование.",
  "Validity verdict": "Вердикт достоверности", "Passed, or flagged for manual review with the reason.": "Пройдено или отправлено на ручную проверку с указанием причины.",
  "Session facts": "Данные сессии", "Items answered, time taken, language, completion date.": "Количество ответов, затраченное время, язык, дата прохождения.",

  "07 — DATA & HONESTY": "07 — ДАННЫЕ И ЧЕСТНОСТЬ", "What is built, and what is not — stated plainly.": "Что уже сделано, а что нет — прямо и честно.",
  "We are pre-calibration. A risk team deserves to know exactly where the line is before signing anything.": "Мы ещё не прошли калибровку. Риск-команда должна точно знать, где проходит граница, прежде чем что-то подписывать.",
  "READY TODAY": "ГОТОВО СЕГОДНЯ", "NOT YET — AND THAT MATTERS": "ЕЩЁ НЕТ — И ЭТО ВАЖНО",
  "500-item bank, translated and reviewed": "Банк из 500 вопросов, переведён и проверен",
  "Built from published behavioural-credit and psychometric literature, in Uzbek, Russian and English.": "Основан на опубликованных исследованиях поведенческого кредитования и психометрии, на узбекском, русском и английском.",
  "Adaptive engine built and running": "Адаптивный движок создан и работает",
  "Item selection responds to each answer, so applicants cannot simply share an answer sheet.": "Подбор вопросов зависит от каждого ответа, поэтому заявители не могут просто передать друг другу готовые ответы.",
  "Validity layer": "Слой достоверности", "Latency, streaks, contradictions and window focus are scored; suspect sessions surface for manual review.": "Оцениваются скорость, серии, противоречия и фокус окна; подозрительные сессии уходят на ручную проверку.",
  "Console and API": "Консоль и API", "Applicant queue, review queue, dimension analytics, and machine-readable results.": "Очередь заявителей, очередь проверки, аналитика по измерениям и машиночитаемые результаты.",
  "Not calibrated on repayment outcomes": "Не откалибровано на данных о погашении",
  "The model has not yet been validated against real default data. Treat the score as an additional signal, never as a decision.": "Модель ещё не проверена на реальных данных о дефолтах. Используйте балл как дополнительный сигнал, а не как решение.",
  "No published AUC or Gini yet": "AUC и Gini пока не опубликованы",
  "We will not quote predictive performance we have not measured. The first pilot produces those numbers.": "Мы не называем точность, которую не измеряли. Эти цифры даст первый пилот.",
  "No formal certification": "Нет формальной сертификации",
  "Personal-data handling follows Uzbek law and contractual terms; independent certification is planned, not held.": "Обработка персональных данных соответствует законодательству Узбекистана и условиям договора; независимая сертификация запланирована, но пока не получена.",
  "No transaction-data feed": "Нет потока транзакционных данных",
  "Bank statement, tax and utility signals are on the roadmap, not in the current model.": "Выписки, налоговые и коммунальные данные есть в планах, но не в текущей модели.",
  "The pilot is the calibration.": "Пилот и есть калибровка.",
  "Run the assessment alongside your existing process on 500–700 applicants. We compare our signal against your repayment outcomes, then recalibrate on your book — at no scoring cost during the pilot window.": "Проведите оценку параллельно с текущим процессом на 500–700 заявителях. Мы сравним наш сигнал с фактическим погашением и перекалибруем модель на вашем портфеле — без оплаты за оценки в период пилота.",
  "Discuss the pilot →": "Обсудить пилот →",
  "RESEARCH BASIS": "НАУЧНАЯ ОСНОВА",
  "The dimensions and item formats follow published field studies. The evidence is mixed, which is why we calibrate on each partner's own repayment data before anyone relies on the score.": "Измерения и форматы вопросов основаны на опубликованных полевых исследованиях. Результаты этих исследований неоднозначны, поэтому мы калибруем модель на данных о погашении каждого партнёра, прежде чем на балл можно будет опираться.",
  "(mixed result)": "(неоднозначный результат)",

  "08 — COMMERCIALS": "08 — УСЛОВИЯ", "Priced per assessment. Institutions only.": "Оплата за каждую оценку. Только для организаций.",
  "We do not sell scores to individuals. Volume moves the per-assessment price; indicative figures below.": "Мы не продаём оценки физическим лицам. Цена зависит от объёма; ориентировочные цифры ниже.",
  "STARTER": "СТАРТ", "BUSINESS": "БИЗНЕС", "ENTERPRISE": "КОРПОРАТИВНЫЙ", "MOST COMMON": "ПОПУЛЯРНЫЙ",
  "UZS per assessment": "сум за оценку", "UZS per assessment · volume tiers": "сум за оценку · по объёму",
  "Custom": "Индивидуально", "per agreement": "по договору",
  "Microfinance, up to 500 assessments a month": "Микрофинансы, до 500 оценок в месяц",
  "Hosted link — no integration needed": "Ссылка на платформе — без интеграции",
  "Results console and review queue": "Консоль результатов и очередь проверки",
  "Three languages out of the box": "Три языка сразу", "Email support": "Поддержка по e-mail",
  "Start the conversation": "Начать разговор",
  "Banks and MFIs running it inside origination": "Банки и МФО, встроившие оценку в процесс выдачи",
  "Everything in Starter": "Всё из тарифа Старт", "REST API and webhooks": "REST API и вебхуки",
  "Admin console: applicants, review, analytics": "Консоль: заявители, проверка, аналитика",
  "Shared pilot criteria and reporting": "Общие критерии пилота и отчётность",
  "Large banks, holdings, state programmes": "Крупные банки, холдинги, государственные программы",
  "White-label and deep core integration": "White-label и глубокая интеграция с АБС",
  "Recalibration on your own book": "Перекалибровка на вашем портфеле",
  "SLA and dedicated support": "SLA и выделенная поддержка",
  "Security and compliance review (ERI, audit)": "Проверка безопасности и комплаенса (ЭЦП, аудит)",
  "Indicative pricing, finalised per agreement. Assessments are delivered through partner institutions, never sold direct to applicants.": "Цены ориентировочные и фиксируются в договоре. Оценки проводятся через партнёрские организации и никогда не продаются заявителям напрямую.",

  "09 — ROADMAP": "09 — ДОРОЖНАЯ КАРТА", "Where we are, and where this goes.": "Где мы сейчас и куда движемся.",
  "Six stages, from a working platform to a national credit profile. We are in Stage 1 now.": "Шесть этапов: от работающей платформы до национального кредитного профиля. Сейчас мы на этапе 1.",
  "DONE": "ГОТОВО", "NOW": "СЕЙЧАС", "NEXT": "ДАЛЕЕ",
  "Platform & method": "Платформа и методика", "Research, 500-item adaptive bank, anti-cheat layer, full platform in three languages.": "Исследования, адаптивный банк из 500 вопросов, защита от обмана, полная платформа на трёх языках.",
  "Data & funding": "Данные и финансирование", "Train on 500–700 real applicants. Partner conversations with banks, MFIs, insurers. Raise.": "Обучение на 500–700 реальных заявителях. Переговоры с банками, МФО и страховщиками. Привлечение инвестиций.",
  "Harden the method": "Укрепление методики", "Fuse behavioural signals with live financial data; continuous recalibration on outcomes.": "Объединение поведенческих сигналов с финансовыми данными; постоянная перекалибровка по результатам.",
  "International": "Международный выход", "Agreements with behavioural fintechs abroad; connect non-bank data — transactions, tax, utilities.": "Соглашения с зарубежными поведенческими финтехами; подключение небанковских данных — транзакции, налоги, коммунальные платежи.",
  "Scale": "Масштабирование", "Contracts across microfinance, insurance and BNPL; commercial banks; state credit programmes.": "Контракты в микрофинансах, страховании и BNPL; коммерческие банки; государственные кредитные программы.",
  "National profile": "Национальный профиль", "An open national credit profile — one trust standard, carried by the person, not the bureau.": "Открытый национальный кредитный профиль — единый стандарт доверия, который принадлежит человеку, а не бюро.",

  "10 — TEAM": "10 — КОМАНДА", "Built by people from inside Uzbek banking.": "Создано людьми из узбекского банковского сектора.",
  "We have sat on the lender's side of the desk and seen creditworthy applicants turned away for lack of a file.": "Мы работали на стороне кредитора и видели, как платёжеспособным заявителям отказывают из-за отсутствия кредитной истории.",
  "FOUNDER · CEO": "ОСНОВАТЕЛЬ · CEO", "CO-FOUNDER": "СООСНОВАТЕЛЬ",
  "Banking and finance: IFRS reporting and expected-credit-loss models, business development, and observer in the SQB privatisation negotiations. ACCA candidate.": "Банки и финансы: отчётность по МСФО и модели ожидаемых кредитных убытков, развитие бизнеса, наблюдатель на переговорах по приватизации SQB. Кандидат ACCA.",
  "Muhriddin Husenov": "Мухриддин Хусенов", "Furqat Ubaydullayev": "Фуркат Убайдуллаев", "Mirshod Raxmatov": "Миршод Рахматов",

  "11 — QUESTIONS": "11 — ВОПРОСЫ", "The questions risk teams ask first.": "Вопросы, которые риск-команды задают первыми.",
  "Something not covered here? Put it in the pilot request and we will answer it directly.": "Не нашли ответ? Напишите в запросе на пилот, и мы ответим напрямую.",
  "Ask us directly →": "Спросить напрямую →",
  "Does this replace our scorecard?": "Это заменяет нашу скоринговую модель?",
  "No. It is an additional input for applicants where your existing scorecard has nothing to work with. It is designed to run alongside your process; you keep full decision authority.": "Нет. Это дополнительный вход для заявителей, по которым вашей модели не на что опереться. Оценка работает параллельно с вашим процессом, а решение всегда остаётся за вами.",
  "What stops an applicant from gaming the answers?": "Что мешает заявителю подстроить ответы?",
  "Three things: items are drawn adaptively from a 500-item bank so sessions differ, contradictory item pairs are distributed through the session, and the validity layer scores response latency, streaks and window focus. Suspect sessions are flagged for review rather than silently scored.": "Три вещи: вопросы выбираются адаптивно из банка в 500 вопросов, поэтому сессии различаются; в сессию встроены пары противоречащих вопросов; слой достоверности оценивает скорость ответов, серии и фокус окна. Подозрительные сессии отправляются на проверку, а не оцениваются молча.",
  "How accurate is it?": "Насколько это точно?",
  "We do not know yet, and we will not invent a number. The model is built on published behavioural-credit research but has not been calibrated against repayment outcomes. The first pilots exist to produce that evidence on real books.": "Пока мы этого не знаем и не будем придумывать цифру. Модель основана на опубликованных исследованиях, но ещё не откалибрована на данных о погашении. Первые пилоты нужны именно для того, чтобы получить эти данные на реальных портфелях.",
  "What data do you need from us?": "Какие данные нужны от нас?",
  "For a pilot: nothing sensitive up front. Applicants complete the assessment through a link. To calibrate, we need repayment outcomes for those applicants at the end of the observation window, under an agreed data-processing arrangement.": "Для пилота заранее — ничего конфиденциального. Заявители проходят оценку по ссылке. Для калибровки в конце периода наблюдения нам нужны данные о погашении по этим заявителям — по согласованному соглашению об обработке данных.",
  "How long does an applicant spend on it?": "Сколько времени тратит заявитель?",
  "10 to 15 minutes, 30–45 adaptive items. It works on a low-end phone and in branch on a tablet, in Uzbek, Russian or English.": "10–15 минут, 30–45 адаптивных вопросов. Работает на простом телефоне и на планшете в отделении, на узбекском, русском или английском.",
  "Can we run it under our own brand?": "Можно использовать под нашим брендом?",
  "Yes, on Enterprise: your brand, your domain, embedded in your existing application journey.": "Да, в тарифе Корпоративный: ваш бренд и домен, встроенные в ваш текущий процесс подачи заявки.",

  "12 — PILOT": "12 — ПИЛОТ", "Put it in front of 500–700 real applicants.": "Проверьте на 500–700 реальных заявителях.",
  "Tell us your portfolio and the segment you keep declining for lack of data. We will come back with a pilot scope, a timeline, and what we need from your side.": "Расскажите о вашем портфеле и сегменте, которому вы отказываете из-за нехватки данных. Мы предложим объём пилота, сроки и то, что потребуется с вашей стороны.",
  "Tashkent, Uzbekistan": "Ташкент, Узбекистан",
  "Full name": "Ф. И. О.", "Institution": "Организация", "Work email": "Рабочий e-mail", "Monthly applications": "Заявок в месяц",
  "Bank or MFI": "Банк или МФО", "Aziz Rahimov": "Азиз Рахимов", "you@bank.uz": "you@bank.uz",
  "Under 500": "До 500", "Over 10 000": "Более 10 000",
  "Which applicants are you turning away for lack of data?": "Каким заявителям вы отказываете из-за нехватки данных?",
  "Sole traders and market vendors with no bureau file…": "ИП и продавцам на рынках без кредитной истории…",
  "We reply within two business days. No applicant data is exchanged before an agreement is signed.": "Мы отвечаем в течение двух рабочих дней. Данные заявителей не передаются до подписания соглашения.",
  "Privacy policy": "Политика конфиденциальности", "Terms of use": "Условия использования",
  "Sending…": "Отправка…", "Request received": "Запрос получен",
  "We will come back within two business days with a proposed pilot scope.": "Мы вернёмся с предложением по пилоту в течение двух рабочих дней.",
  "Anything urgent:": "Срочные вопросы:",

  "Behavioural credit scoring for applicants the bureau cannot see. Pilot stage, Tashkent.": "Поведенческий кредитный скоринг для заявителей, которых не видит бюро. Пилотная стадия, Ташкент.",
  "PRODUCT": "ПРОДУКТ", "COMPANY": "КОМПАНИЯ", "CONTACT": "КОНТАКТЫ",
  "Try the demo": "Демо", "Data & honesty": "Данные и честность",
  "PILOT STAGE · TASHKENT, UZBEKISTAN": "ПИЛОТНАЯ СТАДИЯ · ТАШКЕНТ, УЗБЕКИСТАН",

  "@h1": "Кредитуйте тех, кого ваше бюро <span style=\"position:relative; display:inline-block; color:#FF6A1F\">не видит<span style=\"position:absolute; left:0; right:0; bottom:6px; height:10px; background:rgba(255,106,31,.18); border-radius:3px; z-index:-1\"></span></span>.",
  "@items": "адаптивных вопросов — вопрос <em style=\"font-style:normal; color:var(--t3)\">n+1</em> выбирается по ответу на вопрос <em style=\"font-style:normal; color:var(--t3)\">n</em>",
  "@title": "XulqskorAI — поведенческий кредитный скоринг",
  "@band": {"LOW RISK": "НИЗКИЙ РИСК", "MODERATE": "УМЕРЕННЫЙ", "ELEVATED": "ПОВЫШЕННЫЙ", "HIGH RISK": "ВЫСОКИЙ РИСК", "PARTIAL": "ЧАСТИЧНО", "BAND": "КАТЕГОРИЯ"}
},

uz: {
  "Film": "Video", "Engine": "Dvigatel", "Dimensions": "Oʻlchovlar", "Integration": "Integratsiya",
  "Pricing": "Narxlar", "Roadmap": "Yoʻl xaritasi", "FAQ": "Savollar", "Team": "Jamoa",
  "MENU": "MENYU", "Menu": "Menyu", "Switch theme": "Mavzuni almashtirish", "Sign in": "Kirish",
  "Request a pilot": "Pilot soʻrash", "Request a pilot →": "Pilot soʻrash →",
  "See the engine": "Qanday ishlaydi", "Replay animation": "Animatsiyani qayta koʻrsatish",

  "PILOT PROGRAMME OPEN · TASHKENT": "PILOT DASTUR OCHIQ · TOSHKENT",
  "A 10–15 minute adaptive behavioural assessment returns a six-dimension risk profile for applicants with no credit file — a decision signal where the bureau returns nothing.": "10–15 daqiqalik moslashuvchan xulq-atvor baholashi kredit tarixi boʻlmagan arizachilar uchun olti oʻlchovli risk profilini beradi. Byuro hech narsa bermaydigan joyda qaror uchun signal paydo boʻladi.",
  "item bank": "savollar banki", "dimensions": "oʻlchov", "minutes": "daqiqa", "languages": "til",
  "APPLICANT · UZ-4471": "ARIZACHI · UZ-4471", "APPLICANT UZ-4471": "ARIZACHI UZ-4471",
  "LIVE": "JONLI", "SCORE": "BALL", "Band B · Moderate": "B toifa · Oʻrtacha risk",
  "No bureau file. Strong self-control and planning; conscientiousness below cohort median.": "Byuroda maʼlumot yoʻq. Oʻzini nazorat qilish va rejalashtirish kuchli; masʼuliyatlilik guruh medianasidan past.",
  "VALIDITY · PASSED": "ISHONCHLILIK · OʻTDI", "11m 42s · 38 items": "11 daq 42 son · 38 savol",

  "No credit file required": "Kredit tarixi talab qilinmaydi", "NO CREDIT FILE REQUIRED": "KREDIT TARIXI TALAB QILINMAYDI",
  "Adaptive item selection": "Savollarni moslashuvchan tanlash", "ADAPTIVE ITEM SELECTION": "SAVOLLARNI MOSLASHUVCHAN TANLASH",
  "Anti-cheat validity layer": "Aldovdan himoya qatlami", "ANTI-CHEAT VALIDITY LAYER": "ALDOVDAN HIMOYA QATLAMI",
  "REST API + webhooks": "REST API + webhuklar", "REST API + WEBHOOKS": "REST API + WEBHUKLAR",
  "Six behavioural dimensions": "Olti xulq-atvor oʻlchovi", "SIX BEHAVIOURAL DIMENSIONS": "OLTI XULQ-ATVOR OʻLCHOVI",
  "Result in 10–15 minutes": "Natija 10–15 daqiqada", "RESULT IN 10–15 MINUTES": "NATIJA 10–15 DAQIQADA",
  "Bank-side admin console": "Bank uchun boshqaruv paneli", "BANK-SIDE ADMIN CONSOLE": "BANK UCHUN BOSHQARUV PANELI",

  "FILM — 2 MIN": "VIDEO — 2 DAQ", "Watch the whole idea in two minutes.": "Butun gʻoya ikki daqiqada.",
  "What the assessment looks like from the applicant's side, and what lands on the underwriter's desk.": "Baholash arizachiga qanday koʻrinadi va kredit mutaxassisi qanday natija oladi.",
  "XulqskorAI — how behavioural scoring works": "XulqskorAI — xulq-atvor skoringi qanday ishlaydi",
  "UZ · SUBTITLES RU / EN": "UZ · SUBTITRLAR RU / EN", "XulqskorAI film": "XulqskorAI videosi",

  "FOR APPLICANTS": "ARIZACHILAR UCHUN",
  "Have no credit history? Build a profile that speaks for you.": "Kredit tarixingiz yoʻqmi? Siz haqingizda gapiradigan profil yarating.",
  "Register as an individual or a business, take the assessment once, and carry the result to any partner institution. You decide who sees it — sharing needs a consent code you generate.": "Jismoniy yoki yuridik shaxs sifatida roʻyxatdan oʻting, baholashdan bir marta oʻting va natijani istalgan hamkor tashkilotga taqdim eting. Uni kim koʻrishini siz hal qilasiz: ulashish uchun oʻzingiz yaratgan rozilik kodi kerak.",
  "Create an account": "Hisob yaratish", "Try the assessment": "Baholashni sinab koʻrish",
  "Free for applicants": "Arizachilar uchun bepul", "One attempt every 90 days": "90 kunda bir urinish",
  "Shared only with your consent": "Faqat roziligingiz bilan ulashiladi",
  "A market trader taking the assessment on her phone": "Bozordagi tadbirkor ayol telefonida baholashdan oʻtmoqda",
  "Ten years trading. No credit file.": "Oʻn yil savdoda. Kredit tarixi yoʻq.", "ITEM 12 / 38": "SAVOL 12 / 38",
  "Register": "Roʻyxatdan oʻting", "Phone or email, as an individual or a legal entity. Two minutes.": "Telefon yoki e-pochta orqali, jismoniy yoki yuridik shaxs sifatida. Ikki daqiqa.",
  "Answer the questions": "Savollarga javob bering", "30–45 adaptive items, 10–15 minutes, in your language. No documents.": "30–45 ta moslashuvchan savol, 10–15 daqiqa, oʻz tilingizda. Hujjatlarsiz.",
  "Keep your profile": "Profilingizni saqlang", "Score, six dimensions, personal recommendations, and a shareable consent code.": "Ball, olti oʻlchov, shaxsiy tavsiyalar va ulashish uchun rozilik kodi.",

  "01 — THE GAP": "01 — BOʻSHLIQ", "The file is empty. The person is not.": "Hujjat boʻsh. Inson esa boʻsh emas.",
  "When an applicant has never held a loan, a card, or a registered income stream, the bureau returns a blank. The underwriter is left with a choice between two bad options: decline a creditworthy person, or approve on intuition.": "Arizachi hech qachon kredit, karta yoki rasmiy daromadga ega boʻlmagan boʻlsa, byuro boʻsh javob qaytaradi. Kredit mutaxassisida ikkita yomon yoʻl qoladi: toʻlovga qodir insonni rad etish yoki taxmin bilan maʼqullash.",
  "XulqskorAI produces a structured, comparable signal where none existed — not a replacement for your scorecard, an additional input to it.": "XulqskorAI ilgari hech qanday signal boʻlmagan joyda tuzilmali va taqqoslanadigan signal beradi. U skoring modelingiz oʻrnini bosmaydi, balki unga qoʻshimcha maʼlumot boʻladi.",
  "A credit officer reviewing an application": "Kredit mutaxassisi arizani koʻrib chiqmoqda",
  "BUREAU RESPONSE": "BYURO JAVOBI", "NO RECORDS FOUND": "MAʼLUMOT TOPILMADI",
  "structured risk profile returned to your underwriting queue via API": "ta tuzilmali risk profili API orqali koʻrib chiqish navbatingizga keladi",

  "02 — THE FLOW": "02 — JARAYON", "From application link to underwriting signal.": "Ariza havolasidan qaror signaligacha.",
  "Four stages. No integration required to start — a link works.": "Toʻrt bosqich. Boshlash uchun integratsiya kerak emas — havolaning oʻzi yetarli.",
  "Applicant receives a link": "Arizachi havola oladi",
  "Sent by your officer, embedded in your form, or opened in branch on a tablet. No app, no bureau lookup, no document upload.": "Havolani xodimingiz yuboradi, u arizangiz shakliga joylanadi yoki filialda planshetda ochiladi. Ilova, byuroga soʻrov va hujjat yuklash kerak emas.",
  "Adaptive assessment runs": "Moslashuvchan baholash oʻtkaziladi",
  "Each answer narrows the next item. A 500-item bank means no two sessions follow the same path, which makes answers much harder to memorise or coach.": "Har bir javob keyingi savolni belgilaydi. 500 ta savoldan iborat bank tufayli ikki sessiya bir xil yoʻldan bormaydi, shuning uchun javoblarni yodlab olish yoki oʻrgatish ancha qiyin.",
  "Validity layer screens the session": "Ishonchlilik qatlami sessiyani tekshiradi",
  "Response latency, answer streaks, internal contradictions and window-switching are scored. Suspect sessions are flagged for review, not silently scored.": "Javob tezligi, bir xil javoblar ketma-ketligi, ichki ziddiyatlar va oyna almashtirish baholanadi. Shubhali sessiyalar jimgina baholanmaydi — ular tekshiruvga yuboriladi.",
  "Profile lands in your queue": "Profil navbatingizga tushadi",
  "Overall score, band, six dimension scores, validity verdict and reasoning — in the console or pushed to your systems over the API.": "Umumiy ball, toifa, olti oʻlchov boʻyicha ballar, ishonchlilik xulosasi va izoh — panelda yoki API orqali tizimlaringizda.",
  "ITEM SELECTION · POSTERIOR UPDATE": "SAVOL TANLASH · BAHONI YANGILASH",
  "Response latency": "Javob tezligi", "Answer streaks": "Javoblar ketma-ketligi", "Internal consistency": "Ichki izchillik",
  "Window focus": "Oyna fokusi", "PASS": "OʻTDI", "REVIEW": "TEKSHIRUV",
  "STAGE 00": "BOSQICH 00", "STAGE 01": "BOSQICH 01", "STAGE 02": "BOSQICH 02", "STAGE 03": "BOSQICH 03", "STAGE 04": "BOSQICH 04", "STAGE 05": "BOSQICH 05",

  "03 — THE ENGINE": "03 — DVIGATEL", "Signals in. Behavioural profile out. Matched to your product.": "Kirishda — signallar. Chiqishda — mahsulotingizga moslangan xulq-atvor profili.",
  "Every answer is distributed across six dimensions, checked by the validity layer, then fitted against the risk appetite of the product being applied for.": "Har bir javob olti oʻlchovga taqsimlanadi, ishonchlilik qatlamida tekshiriladi va soʻralayotgan mahsulotning risk ishtahasi bilan solishtiriladi.",
  "Answers": "Javoblar", "500-item adaptive bank": "500 savollik moslashuvchan bank",
  "Response dynamics": "Javob dinamikasi", "latency, hesitation, consistency": "tezlik, ikkilanish, izchillik",
  "Validity checks": "Ishonchlilik tekshiruvlari", "contradiction pairs, window focus": "zid savol juftliklari, oyna fokusi",
  "BEHAVIOURAL": "XULQ-ATVOR", "PRODUCT FIT": "MAHSULOTGA MOSLIK",
  "Microfinance": "Mikromoliya", "Bank loan": "Bank krediti", "BNPL / insurance": "BNPL / sugʻurta",
  "1 · Signal": "1 · Signal", "2 · Profile": "2 · Profil", "3 · Score": "3 · Ball", "4 · Fit": "4 · Moslik",
  "1 · SIGNAL": "1 · SIGNAL", "2 · PROFILE": "2 · PROFIL", "3 · SCORE": "3 · BALL", "4 · FIT": "4 · MOSLIK",

  "04 — WHAT IS MEASURED": "04 — NIMA OʻLCHANADI", "Six dimensions, scored independently.": "Olti oʻlchov, har biri alohida baholanadi.",
  "Each dimension is derived from psychometric constructs in the published behavioural-credit literature and mapped to items in the bank. Hover a dimension to isolate it.": "Har bir oʻlchov xulq-atvorga asoslangan kreditlash boʻyicha nashr etilgan tadqiqotlardagi psixometrik tushunchalarga tayanadi va bankdagi savollarga bogʻlangan. Oʻlchovni ajratib koʻrish uchun kursorni ustiga olib boring.",
  "Responsibility": "Masʼuliyat", "Integrity": "Halollik", "Self-control": "Oʻzini nazorat qilish",
  "Risk control": "Riskni nazorat qilish", "Money habits": "Pul odatlari", "Planning": "Rejalashtirish",
  "Follow-through on commitments — does the applicant finish what they start, and honour arrangements without external pressure?": "Majburiyatlarni bajarish: arizachi boshlagan ishini oxiriga yetkazadimi va kelishuvlarga tashqi bosimsiz rioya qiladimi?",
  "Consistency between stated intent and reported behaviour, cross-checked by contradictory item pairs across the session.": "Bildirilgan niyat va taʼriflangan xatti-harakat oʻrtasidagi muvofiqlik. U sessiya davomida zid savol juftliklari bilan tekshiriladi.",
  "Impulse regulation under pressure: delayed gratification, reaction to windfalls, and spending under emotional load.": "Bosim ostida istaklarni boshqarish: kutilmagan daromadga munosabat, rohatni kechiktira olish va hissiy holatdagi xarajatlar.",
  "Attitude to downside exposure — how the applicant sizes a bet, and whether they hold a buffer against shocks.": "Yoʻqotish xavfiga munosabat: arizachi qancha tavakkal qiladi va kutilmagan holatlar uchun zaxira saqlaydimi.",
  "Everyday money mechanics: tracking, prioritising obligations, and behaviour in a cash shortfall.": "Kundalik pul muomalasi: hisob yuritish, majburiyatlarni ustuvorlik boʻyicha tartiblash va pul yetishmaganda oʻzini tutish.",
  "Horizon length and structure — whether decisions are made against a plan or reactively, month to month.": "Rejalashtirish ufqi va tuzilishi: qarorlar reja asosida qabul qilinadimi yoki oydan oyga vaziyatga qarab.",

  "05 — TRY IT": "05 — SINAB KOʻRING", "Three items. Watch the profile move.": "Uchta savol. Profil qanday oʻzgarishini kuzating.",
  "A miniature of the real assessment — the live version runs 30–45 adaptive items across the full bank.": "Haqiqiy baholashning kichik nusxasi: toʻliq versiya butun bankdan 30–45 ta moslashuvchan savol beradi.",
  "ITEM": "SAVOL", "LIVE PROFILE": "JONLI PROFIL", "AWAITING INPUT": "JAVOB KUTILMOQDA", "Reset": "Qaytadan",
  "A supplier offers a 20% discount if you pay for six months up front. It would take most of your cash buffer.": "Yetkazib beruvchi olti oy uchun oldindan toʻlasangiz 20% chegirma taklif qilmoqda. Bu pul zaxirangizning katta qismini oladi.",
  "Take it — the discount is guaranteed money": "Qabul qilaman — chegirma aniq foyda",
  "Negotiate a smaller prepayment for a partial discount": "Qisman chegirma evaziga kamroq oldindan toʻlov haqida kelishaman",
  "Decline — the buffer is not for this": "Rad etaman — zaxira bunga moʻljallanmagan",
  "A repayment is due on the 10th. On the 8th an urgent family expense comes up that would use the same money.": "Kredit toʻlovi oyning 10-sanasida. 8-sanada xuddi shu pulni talab qiladigan shoshilinch oilaviy xarajat chiqib qoldi.",
  "Call the lender on the 8th and agree a new date": "8-sanada kreditorga qoʻngʻiroq qilib, yangi sana kelishaman",
  "Pay the family expense, tell the lender afterwards": "Oilaviy xarajatni toʻlayman, kreditorga keyin aytaman",
  "Borrow short-term elsewhere to cover both": "Ikkalasini qoplash uchun boshqa joydan qisqa muddatga qarz olaman",
  "Your income this month is 40% above normal.": "Bu oy daromadingiz odatdagidan 40% koʻp.",
  "Buy something that has been waiting a long time": "Anchadan beri kutib yurgan narsamni sotib olaman",
  "Pay ahead on existing obligations": "Mavjud majburiyatlarni muddatidan oldin toʻlayman",
  "Hold it as buffer and decide next month": "Zaxira sifatida saqlab, keyingi oy qaror qilaman",
  "Profile drafted": "Profil tayyor",
  "Three items moved six dimensions. The production assessment runs 30–45 items and adds a validity layer on top.": "Uchta savol olti oʻlchovni oʻzgartirdi. Haqiqiy baholash 30–45 ta savol beradi va ustiga ishonchlilik qatlamini qoʻshadi.",
  "Illustrative only. Scores shown here are produced by a simplified demo function, not the production model.": "Faqat namuna uchun. Bu yerdagi ballarni ishchi model emas, soddalashtirilgan demo funksiya hisoblaydi.",

  "06 — INTEGRATION": "06 — INTEGRATSIYA", "Start with a link. Integrate when you're ready.": "Havoladan boshlang. Tayyor boʻlganingizda integratsiya qiling.",
  "A pilot needs no engineering time on your side: send applicants a link, read results in the console. When the signal proves itself, move it into your origination flow over the API.": "Pilot uchun dasturchilaringiz vaqti kerak emas: arizachilarga havola yuboring va natijalarni panelda koʻring. Signal oʻzini oqlagach, uni API orqali kredit berish jarayoningizga ulang.",
  "Hosted link": "Platformadagi havola", "Per-applicant URL, expires after completion. Zero integration.": "Har bir arizachi uchun alohida havola, baholash tugagach amal qilmaydi. Integratsiya kerak emas.",
  "REST API": "REST API", "Create a session, poll or receive a webhook, pull the full profile.": "Sessiya yarating, webhuk qabul qiling yoki holatni soʻrang va toʻliq profilni oling.",
  "Embedded / white-label": "Joylashtirish / white-label", "Your brand, your domain, inside your existing application journey.": "Mavjud ariza jarayoningiz ichida — sizning brendingiz va domeningiz bilan.",
  "WHAT YOUR SYSTEM RECEIVES": "TIZIMINGIZ NIMA OLADI", "PER APPLICANT": "HAR BIR ARIZACHI UCHUN",
  "Applicant reference": "Arizachi identifikatori", "Your own ID for the person — we never need their name to score them.": "Oʻzingizning ID raqamingiz — baholash uchun bizga insonning ismi kerak emas.",
  "Overall score": "Umumiy ball", "0 – 100, comparable across applicants and over time.": "0 – 100, arizachilar oʻrtasida va vaqt boʻyicha taqqoslanadi.",
  "Band": "Toifa", "A to D, so an officer can act without reading the detail.": "A dan D gacha — xodim tafsilotlarni oʻqimasdan qaror qila oladi.",
  "Six dimension scores": "Olti oʻlchov boʻyicha ballar", "Responsibility, integrity, self-control, risk control, money habits, planning.": "Masʼuliyat, halollik, oʻzini nazorat qilish, riskni nazorat qilish, pul odatlari, rejalashtirish.",
  "Validity verdict": "Ishonchlilik xulosasi", "Passed, or flagged for manual review with the reason.": "Oʻtdi yoki sababi koʻrsatilgan holda qoʻlda tekshiruvga yuborildi.",
  "Session facts": "Sessiya maʼlumotlari", "Items answered, time taken, language, completion date.": "Javob berilgan savollar, sarflangan vaqt, til, yakunlangan sana.",

  "07 — DATA & HONESTY": "07 — MAʼLUMOT VA HALOLLIK", "What is built, and what is not — stated plainly.": "Nima tayyor, nima hali tayyor emas — ochiq aytamiz.",
  "We are pre-calibration. A risk team deserves to know exactly where the line is before signing anything.": "Model hali kalibrlanmagan. Risk jamoasi biror narsani imzolashdan oldin chegara qayerdaligini aniq bilishi kerak.",
  "READY TODAY": "BUGUN TAYYOR", "NOT YET — AND THAT MATTERS": "HALI YOʻQ — VA BU MUHIM",
  "500-item bank, translated and reviewed": "500 savollik bank tarjima qilingan va tekshirilgan",
  "Built from published behavioural-credit and psychometric literature, in Uzbek, Russian and English.": "Xulq-atvorga asoslangan kreditlash va psixometriya boʻyicha nashr etilgan tadqiqotlar asosida tuzilgan; oʻzbek, rus va ingliz tillarida.",
  "Adaptive engine built and running": "Moslashuvchan dvigatel yaratilgan va ishlamoqda",
  "Item selection responds to each answer, so applicants cannot simply share an answer sheet.": "Savollar har bir javobga qarab tanlanadi, shuning uchun arizachilar bir-biriga tayyor javoblarni oddiygina uzata olmaydi.",
  "Validity layer": "Ishonchlilik qatlami", "Latency, streaks, contradictions and window focus are scored; suspect sessions surface for manual review.": "Tezlik, ketma-ketliklar, ziddiyatlar va oyna fokusi baholanadi; shubhali sessiyalar qoʻlda tekshiruvga chiqariladi.",
  "Console and API": "Panel va API", "Applicant queue, review queue, dimension analytics, and machine-readable results.": "Arizachilar navbati, tekshiruv navbati, oʻlchovlar tahlili va mashina oʻqiy oladigan natijalar.",
  "Not calibrated on repayment outcomes": "Toʻlov natijalari asosida kalibrlanmagan",
  "The model has not yet been validated against real default data. Treat the score as an additional signal, never as a decision.": "Model hali real defolt maʼlumotlarida tekshirilmagan. Ballni qaror sifatida emas, faqat qoʻshimcha signal sifatida ishlating.",
  "No published AUC or Gini yet": "AUC va Gini hali eʼlon qilinmagan",
  "We will not quote predictive performance we have not measured. The first pilot produces those numbers.": "Oʻlchamagan aniqlik koʻrsatkichlarini aytmaymiz. Bu raqamlarni birinchi pilot beradi.",
  "No formal certification": "Rasmiy sertifikat yoʻq",
  "Personal-data handling follows Uzbek law and contractual terms; independent certification is planned, not held.": "Shaxsga doir maʼlumotlar Oʻzbekiston qonunchiligi va shartnoma shartlariga muvofiq qayta ishlanadi; mustaqil sertifikatlash rejalashtirilgan, lekin hali olinmagan.",
  "No transaction-data feed": "Tranzaksiya maʼlumotlari ulanmagan",
  "Bank statement, tax and utility signals are on the roadmap, not in the current model.": "Bank koʻchirmalari, soliq va kommunal toʻlov signallari rejada bor, lekin hozirgi modelda yoʻq.",
  "The pilot is the calibration.": "Pilotning oʻzi — kalibrlash.",
  "Run the assessment alongside your existing process on 500–700 applicants. We compare our signal against your repayment outcomes, then recalibrate on your book — at no scoring cost during the pilot window.": "Baholashni mavjud jarayoningiz bilan parallel ravishda 500–700 arizachida oʻtkazing. Signalimizni haqiqiy toʻlov natijalari bilan solishtiramiz va modelni portfelingizda qayta kalibrlaymiz. Pilot davrida baholash uchun toʻlov olinmaydi.",
  "Discuss the pilot →": "Pilotni muhokama qilish →",
  "RESEARCH BASIS": "ILMIY ASOS",
  "The dimensions and item formats follow published field studies. The evidence is mixed, which is why we calibrate on each partner's own repayment data before anyone relies on the score.": "Oʻlchovlar va savol shakllari nashr etilgan dala tadqiqotlariga asoslanadi. Bu tadqiqotlar natijalari bir xil emas, shuning uchun ballga tayanishdan oldin modelni har bir hamkorning oʻz toʻlov maʼlumotlarida kalibrlaymiz.",
  "(mixed result)": "(natija bir xil emas)",

  "08 — COMMERCIALS": "08 — SHARTLAR", "Priced per assessment. Institutions only.": "Har bir baholash uchun toʻlov. Faqat tashkilotlar uchun.",
  "We do not sell scores to individuals. Volume moves the per-assessment price; indicative figures below.": "Jismoniy shaxslarga baho sotmaymiz. Narx hajmga bogʻliq; taxminiy raqamlar quyida.",
  "STARTER": "BOSHLANGʻICH", "BUSINESS": "BIZNES", "ENTERPRISE": "KORPORATIV", "MOST COMMON": "KOʻP TANLANADI",
  "UZS per assessment": "soʻm / baholash", "UZS per assessment · volume tiers": "soʻm / baholash · hajmga qarab",
  "Custom": "Kelishiladi", "per agreement": "shartnoma boʻyicha",
  "Microfinance, up to 500 assessments a month": "Mikromoliya, oyiga 500 tagacha baholash",
  "Hosted link — no integration needed": "Platformadagi havola — integratsiya kerak emas",
  "Results console and review queue": "Natijalar paneli va tekshiruv navbati",
  "Three languages out of the box": "Uch til darhol", "Email support": "E-pochta orqali yordam",
  "Start the conversation": "Muloqotni boshlash",
  "Banks and MFIs running it inside origination": "Baholashni kredit berish jarayoniga ulagan banklar va MMTlar",
  "Everything in Starter": "Boshlangʻich tarifdagi hamma narsa", "REST API and webhooks": "REST API va webhuklar",
  "Admin console: applicants, review, analytics": "Boshqaruv paneli: arizachilar, tekshiruv, tahlil",
  "Shared pilot criteria and reporting": "Pilotning umumiy mezonlari va hisobotlar",
  "Large banks, holdings, state programmes": "Yirik banklar, xoldinglar, davlat dasturlari",
  "White-label and deep core integration": "White-label va asosiy bank tizimi bilan chuqur integratsiya",
  "Recalibration on your own book": "Oʻz portfelingizda qayta kalibrlash",
  "SLA and dedicated support": "SLA va alohida yordam xizmati",
  "Security and compliance review (ERI, audit)": "Xavfsizlik va muvofiqlik tekshiruvi (ERI, audit)",
  "Indicative pricing, finalised per agreement. Assessments are delivered through partner institutions, never sold direct to applicants.": "Narxlar taxminiy, yakuniy narx shartnomada belgilanadi. Baholash hamkor tashkilotlar orqali oʻtkaziladi va arizachilarga toʻgʻridan-toʻgʻri sotilmaydi.",

  "09 — ROADMAP": "09 — YOʻL XARITASI", "Where we are, and where this goes.": "Hozir qayerdamiz va qayerga boramiz.",
  "Six stages, from a working platform to a national credit profile. We are in Stage 1 now.": "Ishlayotgan platformadan milliy kredit profiligacha olti bosqich. Hozir 1-bosqichdamiz.",
  "DONE": "BAJARILDI", "NOW": "HOZIR", "NEXT": "KEYINGI",
  "Platform & method": "Platforma va metodika", "Research, 500-item adaptive bank, anti-cheat layer, full platform in three languages.": "Tadqiqot, 500 savollik moslashuvchan bank, aldovdan himoya qatlami, uch tildagi toʻliq platforma.",
  "Data & funding": "Maʼlumot va moliyalashtirish", "Train on 500–700 real applicants. Partner conversations with banks, MFIs, insurers. Raise.": "500–700 real arizachida oʻqitish. Banklar, MMTlar va sugʻurta kompaniyalari bilan muzokaralar. Investitsiya jalb qilish.",
  "Harden the method": "Metodikani mustahkamlash", "Fuse behavioural signals with live financial data; continuous recalibration on outcomes.": "Xulq-atvor signallarini moliyaviy maʼlumotlar bilan birlashtirish; natijalar asosida doimiy qayta kalibrlash.",
  "International": "Xalqaro bozor", "Agreements with behavioural fintechs abroad; connect non-bank data — transactions, tax, utilities.": "Xorijdagi xulq-atvor fintexlari bilan kelishuvlar; bankdan tashqari maʼlumotlarni ulash — tranzaksiyalar, soliq, kommunal toʻlovlar.",
  "Scale": "Kengayish", "Contracts across microfinance, insurance and BNPL; commercial banks; state credit programmes.": "Mikromoliya, sugʻurta va BNPL sohalarida shartnomalar; tijorat banklari; davlat kredit dasturlari.",
  "National profile": "Milliy profil", "An open national credit profile — one trust standard, carried by the person, not the bureau.": "Ochiq milliy kredit profili — byuroga emas, insonning oʻziga tegishli yagona ishonch standarti.",

  "10 — TEAM": "10 — JAMOA", "Built by people from inside Uzbek banking.": "Oʻzbekiston bank sohasidan chiqqan jamoa yaratgan.",
  "We have sat on the lender's side of the desk and seen creditworthy applicants turned away for lack of a file.": "Biz kreditor tomonida ishlaganmiz va toʻlovga qodir arizachilar kredit tarixi yoʻqligi uchun rad etilganini koʻrganmiz.",
  "FOUNDER · CEO": "ASOSCHI · CEO", "CO-FOUNDER": "HAMMUASSIS",
  "Banking and finance: IFRS reporting and expected-credit-loss models, business development, and observer in the SQB privatisation negotiations. ACCA candidate.": "Bank va moliya: MHXS hisobotlari va kutilayotgan kredit zararlari modellari, biznesni rivojlantirish, SQB xususiylashtirish muzokaralarida kuzatuvchi. ACCA nomzodi.",

  "11 — QUESTIONS": "11 — SAVOLLAR", "The questions risk teams ask first.": "Risk jamoalari birinchi beradigan savollar.",
  "Something not covered here? Put it in the pilot request and we will answer it directly.": "Javob topilmadimi? Savolingizni pilot soʻroviga yozing, toʻgʻridan-toʻgʻri javob beramiz.",
  "Ask us directly →": "Bizdan soʻrang →",
  "Does this replace our scorecard?": "Bu skoring modelimiz oʻrnini bosadimi?",
  "No. It is an additional input for applicants where your existing scorecard has nothing to work with. It is designed to run alongside your process; you keep full decision authority.": "Yoʻq. Bu mavjud modelingizda maʼlumot boʻlmagan arizachilar uchun qoʻshimcha manba. U jarayoningiz bilan parallel ishlaydi, yakuniy qaror esa doim sizda qoladi.",
  "What stops an applicant from gaming the answers?": "Arizachi javoblarni sunʼiy moslashtira olmaydimi?",
  "Three things: items are drawn adaptively from a 500-item bank so sessions differ, contradictory item pairs are distributed through the session, and the validity layer scores response latency, streaks and window focus. Suspect sessions are flagged for review rather than silently scored.": "Buning uchta toʻsigʻi bor. Savollar 500 savollik bankdan moslashuvchan tanlanadi, shuning uchun sessiyalar bir-biridan farq qiladi. Sessiya davomida zid savol juftliklari beriladi. Ishonchlilik qatlami javob tezligi, ketma-ketliklar va oyna fokusini baholaydi. Shubhali sessiyalar jimgina baholanmaydi — ular tekshiruvga yuboriladi.",
  "How accurate is it?": "Qanchalik aniq?",
  "We do not know yet, and we will not invent a number. The model is built on published behavioural-credit research but has not been calibrated against repayment outcomes. The first pilots exist to produce that evidence on real books.": "Hozircha bilmaymiz va raqam oʻylab topmaymiz. Model nashr etilgan tadqiqotlarga asoslangan, lekin hali toʻlov natijalari asosida kalibrlanmagan. Birinchi pilotlar aynan shu dalilni real portfellarda olish uchun kerak.",
  "What data do you need from us?": "Bizdan qanday maʼlumot kerak?",
  "For a pilot: nothing sensitive up front. Applicants complete the assessment through a link. To calibrate, we need repayment outcomes for those applicants at the end of the observation window, under an agreed data-processing arrangement.": "Pilot boshida hech qanday maxfiy maʼlumot kerak emas. Arizachilar baholashdan havola orqali oʻtadi. Kalibrlash uchun kuzatuv davri oxirida shu arizachilarning toʻlov natijalari kerak boʻladi — kelishilgan maʼlumotlarni qayta ishlash shartnomasi asosida.",
  "How long does an applicant spend on it?": "Arizachi qancha vaqt sarflaydi?",
  "10 to 15 minutes, 30–45 adaptive items. It works on a low-end phone and in branch on a tablet, in Uzbek, Russian or English.": "10–15 daqiqa, 30–45 ta moslashuvchan savol. Oddiy telefonda ham, filialdagi planshetda ham ishlaydi; oʻzbek, rus yoki ingliz tilida.",
  "Can we run it under our own brand?": "Uni oʻz brendimiz ostida ishlata olamizmi?",
  "Yes, on Enterprise: your brand, your domain, embedded in your existing application journey.": "Ha, Korporativ tarifda: sizning brendingiz va domeningiz bilan, mavjud ariza jarayoningiz ichida.",

  "12 — PILOT": "12 — PILOT", "Put it in front of 500–700 real applicants.": "500–700 real arizachida sinab koʻring.",
  "Tell us your portfolio and the segment you keep declining for lack of data. We will come back with a pilot scope, a timeline, and what we need from your side.": "Portfelingiz va maʼlumot yetishmagani uchun rad etayotgan segmentingiz haqida yozing. Biz pilot hajmi, muddatlari va siz tomondan nima kerakligi haqida taklif bilan qaytamiz.",
  "Tashkent, Uzbekistan": "Toshkent, Oʻzbekiston",
  "Full name": "F. I. Sh.", "Institution": "Tashkilot", "Work email": "Ish e-pochtasi", "Monthly applications": "Oylik arizalar soni",
  "Bank or MFI": "Bank yoki MMT", "you@bank.uz": "you@bank.uz",
  "Under 500": "500 dan kam", "Over 10 000": "10 000 dan koʻp",
  "Which applicants are you turning away for lack of data?": "Maʼlumot yetishmagani uchun qaysi arizachilarni rad etyapsiz?",
  "Sole traders and market vendors with no bureau file…": "Kredit tarixi yoʻq yakka tartibdagi tadbirkorlar va bozor sotuvchilari…",
  "We reply within two business days. No applicant data is exchanged before an agreement is signed.": "Ikki ish kuni ichida javob beramiz. Shartnoma imzolanmaguncha arizachilar maʼlumoti almashilmaydi.",
  "Privacy policy": "Maxfiylik siyosati", "Terms of use": "Foydalanish shartlari",
  "Sending…": "Yuborilmoqda…", "Request received": "Soʻrov qabul qilindi",
  "We will come back within two business days with a proposed pilot scope.": "Ikki ish kuni ichida pilot boʻyicha taklif bilan qaytamiz.",
  "Anything urgent:": "Shoshilinch savollar uchun:",

  "Behavioural credit scoring for applicants the bureau cannot see. Pilot stage, Tashkent.": "Byuro koʻra olmaydigan arizachilar uchun xulq-atvorga asoslangan kredit skoringi. Pilot bosqichi, Toshkent.",
  "PRODUCT": "MAHSULOT", "COMPANY": "KOMPANIYA", "CONTACT": "ALOQA",
  "Try the demo": "Demo", "Data & honesty": "Maʼlumot va halollik",
  "PILOT STAGE · TASHKENT, UZBEKISTAN": "PILOT BOSQICHI · TOSHKENT, OʻZBEKISTON",

  "@h1": "Byuro <span style=\"position:relative; display:inline-block; color:#FF6A1F\">koʻrmaydigan<span style=\"position:absolute; left:0; right:0; bottom:6px; height:10px; background:rgba(255,106,31,.18); border-radius:3px; z-index:-1\"></span></span> insonlarga kredit bering.",
  "@items": "ta moslashuvchan savolga javob berildi: <em style=\"font-style:normal; color:var(--t3)\">n+1</em>-savol <em style=\"font-style:normal; color:var(--t3)\">n</em>-savolga berilgan javobga qarab tanlanadi",
  "@title": "XulqskorAI — xulq-atvorga asoslangan kredit skoringi",
  "@band": {"LOW RISK": "PAST RISK", "MODERATE": "OʻRTACHA", "ELEVATED": "YUQORIROQ", "HIGH RISK": "YUQORI RISK", "PARTIAL": "QISMAN", "BAND": "TOIFA"}
}
};

/* ---- runtime: translate text nodes and attributes of the landing in place ---- */
(function () {
  var ORIG = new WeakMap(), WROTE = new WeakMap(), AORIG = new WeakMap(), HORIG = new WeakMap();
  var ATTRS = ['placeholder', 'alt', 'aria-label', 'title'];
  var lang = 'en', busy = false, EN_TITLE = document.title;
  function band(k, d) {
    var m = k.match(/^BAND ([A-D]) · (LOW RISK|MODERATE|ELEVATED|HIGH RISK)( · PARTIAL)?$/);
    if (!m || !d['@band']) return null;
    var b = d['@band'];
    return (lang === 'uz' ? m[1] + ' ' + b.BAND : b.BAND + ' ' + m[1]) + ' · ' + b[m[2]] + (m[3] ? ' · ' + b.PARTIAL : '');
  }
  function tr(s) {
    if (lang === 'en' || !s) return s;
    var d = window.XS_TR[lang]; if (!d) return s;
    var k = s.trim(); if (!k) return s;
    var v = Object.prototype.hasOwnProperty.call(d, k) ? d[k] : band(k, d);
    if (v == null) return s;
    return s.match(/^\s*/)[0] + v + s.match(/\s*$/)[0];
  }
  function doText(n) {
    var p = n.parentElement; if (!p || p.closest('script,style,[data-xs-html]')) return;
    var cur = n.nodeValue;
    if (!ORIG.has(n) || (WROTE.get(n) !== cur && ORIG.get(n) !== cur)) ORIG.set(n, cur);
    var out = tr(ORIG.get(n));
    if (out !== cur) { n.nodeValue = out; }
    WROTE.set(n, out);
  }
  function doEl(el) {
    if (el.hasAttribute && el.hasAttribute('data-xs-html')) {
      if (!HORIG.has(el)) HORIG.set(el, el.innerHTML);
      var d = window.XS_TR[lang], key = '@' + el.getAttribute('data-xs-html');
      var html = (lang !== 'en' && d && d[key]) ? d[key] : HORIG.get(el);
      if (el.innerHTML !== html) el.innerHTML = html;
    }
    for (var i = 0; i < ATTRS.length; i++) {
      var a = ATTRS[i]; if (!el.hasAttribute || !el.hasAttribute(a)) continue;
      var m = AORIG.get(el) || {}; if (!(a in m)) { m[a] = el.getAttribute(a); AORIG.set(el, m); }
      var v = tr(m[a]); if (el.getAttribute(a) !== v) el.setAttribute(a, v);
    }
  }
  function walk(root) {
    if (!root) return;
    busy = true;
    try {
      if (root.nodeType === 3) { doText(root); return; }
      if (root.nodeType !== 1) return;
      doEl(root);
      root.querySelectorAll('[data-xs-html],[placeholder],[alt],[aria-label],[title]').forEach(doEl);
      var w = document.createTreeWalker(root, NodeFilter.SHOW_TEXT), n;
      while ((n = w.nextNode())) doText(n);
    } finally { busy = false; }
  }
  function roots() { return ['xsNav', 'xsDrawer', 'xsSite'].map(function (id) { return document.getElementById(id); }).filter(Boolean); }
  window.xsApplyLang = function (l) {
    lang = (l === 'ru' || l === 'uz') ? l : 'en';
    roots().forEach(walk);
    var d = window.XS_TR[lang];
    document.title = (lang !== 'en' && d && d['@title']) ? d['@title'] : EN_TITLE;
  };
  var obs = new MutationObserver(function (muts) {
    if (busy || lang === 'en') return;
    var todo = [];
    muts.forEach(function (m) {
      if (m.type === 'characterData') todo.push(m.target);
      else m.addedNodes.forEach(function (n) { todo.push(n); });
    });
    todo.forEach(walk);
  });
  function start() {
    roots().forEach(function (r) { obs.observe(r, { childList: true, subtree: true, characterData: true }); });
    var cur = (typeof LANG !== 'undefined') ? LANG : 'en';
    window.xsApplyLang(cur);
    var sl = window.setLang;
    if (typeof sl === 'function' && !sl._xsI18n) {
      window.setLang = function (l) { var r = sl.apply(this, arguments); try { window.xsApplyLang(l); } catch (e) {} return r; };
      window.setLang._xsI18n = true;
    }
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', function () { setTimeout(start, 0); });
  else setTimeout(start, 0);
})();
